name: Build Docker Image

# 手动触发工作流
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的最新 Ubuntu 环境

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Docker Buildx 环境，确保 Docker 可支持多平台构建
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录 Docker Hub（可选，视乎你是否需要将镜像推送到 Docker Hub）
      - name: jiwei
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 用户名
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub 密码或令牌

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build --build-arg NODE_VERSION=20 -t only10chat:newest .

      # 推送镜像到 Docker Hub（如果需要）
      - name: Push Docker image
        run: |
          docker push only10chat:newest
